# Generated by Django 3.2.14 on 2022-08-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('ex_1', models.CharField(default='보기 없음', max_length=100)),
                ('ex_2', models.CharField(default='보기 없음', max_length=100)),
                ('ex_3', models.CharField(default='보기 없음', max_length=100)),
                ('ex_4', models.CharField(default='보기 없음', max_length=100)),
                ('answer', models.IntegerField(default=0)),
                ('participants', models.IntegerField(default=0)),
                ('correct_person', models.IntegerField(default=0)),
            ],
        ),
    ]
